addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y build-essential git cmake libboost-all-dev
script: make test-release
